export const sqlErrorMap = {
    50009: {statusCode: 409, message: 'TIN number already registered'},
    50010: {statusCode: 409, message: 'Email address already registered'},
    50019: {statusCode: 409, message: 'You have already submitted an enrollment'},
    50020: {statusCode: 404, message: 'Beneficiary not found'},
    50021: {statusCode: 409, message: 'This enrollment already has a beneficiary with that name'},
    50022: {statusCode: 409, message: 'Beneficiary could not be updated'},
    50024: {statusCode: 409, message: 'TIN number already registered'},
    50025: {statusCode: 409, message: 'Email address already registered'},
    50035: {statusCode: 409, message: 'Employee ID number already registered'},
    50036: {statusCode: 409, message: 'Email address already registered'},
    50037: { statusCode: 401, message: 'Invalid credentials' },
    50040: { statusCode: 404, message: 'User does not exist or is inactive' },
    50041: { statusCode: 409, message: 'User could not be updated' },
    50073: { statusCode: 403, message: 'Only HR users can manage enrollment invitations' },
    50074: { statusCode: 404, message: 'Active enrollment invitation does not exist' },
    50075: { statusCode: 404, message: 'Active enrollment invitation does not exist' },
    50077: { statusCode: 404, message: 'Enrollment invitation does not exist' },
    50078: { statusCode: 409, message: 'This person has already completed an enrollment' },
    2627: {statusCode: 409, message: 'Duplicate record'},
}